CREATE TABLE "PUBLIC"."APPOINTMENT"
(
   ID bigint PRIMARY KEY NOT NULL,
   END_TIME timestamp NOT NULL,
   START_TIME timestamp NOT NULL
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON "PUBLIC"."APPOINTMENT"(ID)
;
CREATE TABLE "PUBLIC"."AVAILABILITY"
(
   ID bigint PRIMARY KEY NOT NULL,
   END_TIME timestamp NOT NULL,
   START_TIME timestamp NOT NULL
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON "PUBLIC"."AVAILABILITY"(ID)
;
CREATE TABLE "PUBLIC"."CLINIC"
(
   ID bigint PRIMARY KEY NOT NULL,
   NAME varchar(200) NOT NULL
)
;
CREATE UNIQUE INDEX UK_4OKSLEUSU4WKSQJPFTWJQBJ0M_INDEX_7 ON "PUBLIC"."CLINIC"(NAME)
;
CREATE UNIQUE INDEX PRIMARY_KEY_7 ON "PUBLIC"."CLINIC"(ID)
;
CREATE TABLE "PUBLIC"."PATIENT"
(
   ID bigint PRIMARY KEY NOT NULL,
   FIRST_NAME varchar(200) NOT NULL,
   LAST_NAME varchar(200) NOT NULL,
   UNIQUE_ID varchar(400) NOT NULL,
   CLINIC_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."PATIENT"
ADD CONSTRAINT FKRG813T22W4H0MX4BHGKWYVJL9
FOREIGN KEY (CLINIC_ID)
REFERENCES "PUBLIC"."CLINIC"(ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_F ON "PUBLIC"."PATIENT"(ID)
;
CREATE INDEX FKRG813T22W4H0MX4BHGKWYVJL9_INDEX_F ON "PUBLIC"."PATIENT"(CLINIC_ID)
;
CREATE UNIQUE INDEX UK_5T16YS5B7AYTU8OLS5D5I71QJ_INDEX_F ON "PUBLIC"."PATIENT"(UNIQUE_ID)
;
CREATE TABLE "PUBLIC"."PATIENT_APPOINTMENTS"
(
   PATIENT_ID bigint NOT NULL,
   APPOINTMENTS_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."PATIENT_APPOINTMENTS"
ADD CONSTRAINT FKT56RRBFNR2FB40BSETCK8YP24
FOREIGN KEY (APPOINTMENTS_ID)
REFERENCES "PUBLIC"."APPOINTMENT"(ID)
;
ALTER TABLE "PUBLIC"."PATIENT_APPOINTMENTS"
ADD CONSTRAINT FK9T5466BJRP5L4IKQLWQ7MY18M
FOREIGN KEY (PATIENT_ID)
REFERENCES "PUBLIC"."PATIENT"(ID)
;
CREATE INDEX FK9T5466BJRP5L4IKQLWQ7MY18M_INDEX_C ON "PUBLIC"."PATIENT_APPOINTMENTS"(PATIENT_ID)
;
CREATE UNIQUE INDEX UK_ELIUMJ45N5S6LQD325U36MYGC_INDEX_C ON "PUBLIC"."PATIENT_APPOINTMENTS"(APPOINTMENTS_ID)
;
CREATE TABLE "PUBLIC"."PROFESSIONAL"
(
   ID bigint PRIMARY KEY NOT NULL,
   FIRST_NAME varchar(200) NOT NULL,
   LAST_NAME varchar(200) NOT NULL,
   UNIQUE_ID varchar(400) NOT NULL,
   CLINIC_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."PROFESSIONAL"
ADD CONSTRAINT FKOE74PQV15414P1K6X4CXRN8M3
FOREIGN KEY (CLINIC_ID)
REFERENCES "PUBLIC"."CLINIC"(ID)
;
CREATE UNIQUE INDEX UK_RV51I484KH2G0PUFGKRHYGU7V_INDEX_B ON "PUBLIC"."PROFESSIONAL"(UNIQUE_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_B ON "PUBLIC"."PROFESSIONAL"(ID)
;
CREATE INDEX FKOE74PQV15414P1K6X4CXRN8M3_INDEX_B ON "PUBLIC"."PROFESSIONAL"(CLINIC_ID)
;
CREATE TABLE "PUBLIC"."PROFESSIONAL_APPOINTMENTS"
(
   PROFESSIONAL_ID bigint NOT NULL,
   APPOINTMENTS_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."PROFESSIONAL_APPOINTMENTS"
ADD CONSTRAINT FKRA9934I57POT1NISR5S03KO1V
FOREIGN KEY (APPOINTMENTS_ID)
REFERENCES "PUBLIC"."APPOINTMENT"(ID)
;
ALTER TABLE "PUBLIC"."PROFESSIONAL_APPOINTMENTS"
ADD CONSTRAINT FK1KQOSB9TA6VUEGWI6MF47D7EK
FOREIGN KEY (PROFESSIONAL_ID)
REFERENCES "PUBLIC"."PROFESSIONAL"(ID)
;
CREATE UNIQUE INDEX UK_N9WEWD6SH6HFGU6HNV6Y56PR7_INDEX_D ON "PUBLIC"."PROFESSIONAL_APPOINTMENTS"(APPOINTMENTS_ID)
;
CREATE INDEX FK1KQOSB9TA6VUEGWI6MF47D7EK_INDEX_D ON "PUBLIC"."PROFESSIONAL_APPOINTMENTS"(PROFESSIONAL_ID)
;
CREATE TABLE "PUBLIC"."PROFESSIONAL_AVAILABILITIES"
(
   PROFESSIONAL_ID bigint NOT NULL,
   AVAILABILITIES_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."PROFESSIONAL_AVAILABILITIES"
ADD CONSTRAINT FKJWPYVJ8S3KGHS82LUKBEOB6JI
FOREIGN KEY (PROFESSIONAL_ID)
REFERENCES "PUBLIC"."PROFESSIONAL"(ID)
;
ALTER TABLE "PUBLIC"."PROFESSIONAL_AVAILABILITIES"
ADD CONSTRAINT FKGXMCG92VUBJ6KU0BLRRJ3K46Q
FOREIGN KEY (AVAILABILITIES_ID)
REFERENCES "PUBLIC"."AVAILABILITY"(ID)
;
CREATE UNIQUE INDEX UK_R0H5YX9F1RH3WB55L7XQOEVXK_INDEX_8 ON "PUBLIC"."PROFESSIONAL_AVAILABILITIES"(AVAILABILITIES_ID)
;
CREATE INDEX FKJWPYVJ8S3KGHS82LUKBEOB6JI_INDEX_8 ON "PUBLIC"."PROFESSIONAL_AVAILABILITIES"(PROFESSIONAL_ID)
;
